import { Frequency } from '../options.ts';
import { formatLocalizedDate, formatTzAbbreviation, joinList, type ToTextLocaleDefinition } from './shared.ts';

const WEEKDAY_NAMES_AR = ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد'] as const;
const MONTH_NAMES_AR = ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'] as const;
const WORKWEEK_AR = ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة'] as const;
function formatArabicWallTime(hour: number, minute: number, second: number) { if (second) return `${hour}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`; if (minute) return `${hour}:${String(minute).padStart(2, '0')}`; return `${hour}`; }
export const AR_LOCALE: ToTextLocaleDefinition = {
  intl: 'ar', weekdayNames: WEEKDAY_NAMES_AR, monthNames: MONTH_NAMES_AR, conjunction: 'و', customSource: 'مصدر مخصص', customSet: 'مجموعة مخصصة', weekdayShortcut: 'يوم عمل',
  everyUnit(freq, interval) { switch (freq) { case Frequency.YEARLY: return interval === 1 ? 'كل سنة' : `كل ${interval} سنوات`; case Frequency.MONTHLY: return interval === 1 ? 'كل شهر' : `كل ${interval} أشهر`; case Frequency.WEEKLY: return interval === 1 ? 'كل أسبوع' : `كل ${interval} أسابيع`; case Frequency.DAILY: return interval === 1 ? 'كل يوم' : `كل ${interval} أيام`; case Frequency.HOURLY: return interval === 1 ? 'كل ساعة' : `كل ${interval} ساعات`; case Frequency.MINUTELY: return interval === 1 ? 'كل دقيقة' : `كل ${interval} دقائق`; case Frequency.SECONDLY: return interval === 1 ? 'كل ثانية' : `كل ${interval} ثوان`; } },
  ordinalNumber(value) { if (value < 0) return value === -1 ? 'الأخير' : `${Math.abs(value)} الأخير`; return `${value}`; },
  formatWeekday(value) { const name = WEEKDAY_NAMES_AR[value.weekday]!; if (!value.ordinal) return name; if (value.ordinal === -1) return `الأخير ${name}`; return `${value.ordinal} ${name}`; },
  formatWallTime: formatArabicWallTime,
  formatDate(date, tzid) { return formatLocalizedDate(date, tzid, 'ar'); }, tzAbbreviation(date, tzid) { return formatTzAbbreviation(date, tzid, 'ar'); }, countPhrase(count) { return `${count} ${count === 1 ? 'مرة' : 'مرات'}`; }, dateCountPhrase(count, additional) { return additional ? `${count} ${count === 1 ? 'تاريخ إضافي' : 'تواريخ إضافية'}` : `${count} ${count === 1 ? 'تاريخ' : 'تواريخ'}`; }, sourceDateCountPhrase(count) { return `${count} ${count === 1 ? 'تاريخ' : 'تواريخ'}`; }, withAdditionalDates(count) { return `مع ${count} ${count === 1 ? 'تاريخ إضافي' : 'تواريخ إضافية'}`; }, excludingDates(count) { return `باستثناء ${count} ${count === 1 ? 'تاريخ' : 'تواريخ'}`; }, excludingPhrase(value) { return `باستثناء ${value}`; }, exceptPhrase(value) { return `إلا ${value}`; }, weekPhrase(value) { return `في الأسبوع ${value}`; }, monthsPhrase(months) { return `في ${months}`; }, weekdaysPhrase(weekdays) { return `في ${joinList(weekdays, 'و', 'ar')}`; }, monthDaysPhrase(days) { return `في اليوم ${joinList(days, 'و', 'ar')} من الشهر`; }, yearDaysPhrase(days) { return `في اليوم ${joinList(days, 'و', 'ar')} من السنة`; }, timePhrase(times) { return `عند ${times}`; }, minutesPhrase(minutes) { return `في الدقيقة ${minutes}`; }, secondsPhrase(seconds) { return `في الثانية ${seconds}`; }, untilPhrase(date) { return `حتى ${date}`; }, countLimitPhrase(count) { return `لمدة ${count} ${count === 1 ? 'مرة' : 'مرات'}`; }, dtstartPhrase(date) { return `ابتداءً من ${date}`; }, setPosPhrase(instances, count) { return `في ${instances} ${count === 1 ? 'مرة' : 'مرات'}`; }, weekStartsOnPhrase(weekday) { return `يبدأ الأسبوع يوم ${weekday}`; }, rscalePhrase(rscale, skip) { return `(RSCALE=${rscale}${skip ? `;SKIP=${skip}` : ''})`; }, mergeWeekdayShortcut(weekdays) { const sorted = [...weekdays].sort(); const expected = [...WORKWEEK_AR].sort(); return sorted.length === expected.length && sorted.every((day, index) => day === expected[index]) ? 'يوم عمل' : null; }, weekdayShortcutPhrase() { return 'كل يوم عمل'; },
};
