import { Frequency } from '../options.ts';
import { formatLocalizedDate, formatTzAbbreviation, joinList, type ToTextLocaleDefinition } from './shared.ts';
const WEEKDAY_NAMES_HE = ['יום שני', 'יום שלישי', 'יום רביעי', 'יום חמישי', 'יום שישי', 'יום שבת', 'יום ראשון'] as const;
const MONTH_NAMES_HE = ['ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר'] as const;
const WORKWEEK_HE = ['יום שני', 'יום שלישי', 'יום רביעי', 'יום חמישי', 'יום שישי'] as const;
function formatHebrewWallTime(hour: number, minute: number, second: number) { if (second) return `${hour}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`; if (minute) return `${hour}:${String(minute).padStart(2, '0')}`; return `${hour}`; }
export const HE_LOCALE: ToTextLocaleDefinition = {
  intl: 'he', weekdayNames: WEEKDAY_NAMES_HE, monthNames: MONTH_NAMES_HE, conjunction: 'ו', customSource: 'מקור מותאם', customSet: 'קבוצה מותאמת', weekdayShortcut: 'יום חול',
  everyUnit(freq, interval) { switch (freq) { case Frequency.YEARLY: return interval === 1 ? 'כל שנה' : `כל ${interval} שנים`; case Frequency.MONTHLY: return interval === 1 ? 'כל חודש' : `כל ${interval} חודשים`; case Frequency.WEEKLY: return interval === 1 ? 'כל שבוע' : `כל ${interval} שבועות`; case Frequency.DAILY: return interval === 1 ? 'כל יום' : `כל ${interval} ימים`; case Frequency.HOURLY: return interval === 1 ? 'כל שעה' : `כל ${interval} שעות`; case Frequency.MINUTELY: return interval === 1 ? 'כל דקה' : `כל ${interval} דקות`; case Frequency.SECONDLY: return interval === 1 ? 'כל שנייה' : `כל ${interval} שניות`; } },
  ordinalNumber(value) { if (value < 0) return value === -1 ? 'אחרון' : `${Math.abs(value)} אחרון`; return `${value}`; },
  formatWeekday(value) { const name = WEEKDAY_NAMES_HE[value.weekday]!; if (!value.ordinal) return name; if (value.ordinal === -1) return `${name} אחרון`; return `${value.ordinal} ${name}`; },
  formatWallTime: formatHebrewWallTime,
  formatDate(date, tzid) { return formatLocalizedDate(date, tzid, 'he'); }, tzAbbreviation(date, tzid) { return formatTzAbbreviation(date, tzid, 'he'); }, countPhrase(count) { return `${count} ${count === 1 ? 'פעם' : 'פעמים'}`; }, dateCountPhrase(count, additional) { return additional ? `${count} ${count === 1 ? 'תאריך נוסף' : 'תאריכים נוספים'}` : `${count} ${count === 1 ? 'תאריך' : 'תאריכים'}`; }, sourceDateCountPhrase(count) { return `${count} ${count === 1 ? 'תאריך' : 'תאריכים'}`; }, withAdditionalDates(count) { return `עם ${count} ${count === 1 ? 'תאריך נוסף' : 'תאריכים נוספים'}`; }, excludingDates(count) { return `למעט ${count} ${count === 1 ? 'תאריך' : 'תאריכים'}`; }, excludingPhrase(value) { return `למעט ${value}`; }, exceptPhrase(value) { return `חוץ מ-${value}`; }, weekPhrase(value) { return `בשבוע ${value}`; }, monthsPhrase(months) { return `ב${months}`; }, weekdaysPhrase(weekdays) { return `ב ${joinList(weekdays, 'ו', 'he')}`; }, monthDaysPhrase(days) { return `ביום ${joinList(days, 'ו', 'he')} של החודש`; }, yearDaysPhrase(days) { return `ביום ${joinList(days, 'ו', 'he')} של השנה`; }, timePhrase(times) { return `בשעה ${times}`; }, minutesPhrase(minutes) { return `בדקה ${minutes}`; }, secondsPhrase(seconds) { return `בשנייה ${seconds}`; }, untilPhrase(date) { return `עד ${date}`; }, countLimitPhrase(count) { return `למשך ${count} ${count === 1 ? 'פעם' : 'פעמים'}`; }, dtstartPhrase(date) { return `החל מ-${date}`; }, setPosPhrase(instances, count) { return `ב${instances} ${count === 1 ? 'פעם' : 'פעמים'}`; }, weekStartsOnPhrase(weekday) { return `השבוע מתחיל ב${weekday}`; }, rscalePhrase(rscale, skip) { return `(RSCALE=${rscale}${skip ? `;SKIP=${skip}` : ''})`; }, mergeWeekdayShortcut(weekdays) { const sorted = [...weekdays].sort(); const expected = [...WORKWEEK_HE].sort(); return sorted.length === expected.length && sorted.every((day, index) => day === expected[index]) ? 'יום חול' : null; }, weekdayShortcutPhrase() { return 'כל יום חול'; },
};
