import { Frequency } from '../options.ts';
import { formatLocalizedDate, formatTzAbbreviation, joinList, type ToTextLocaleDefinition } from './shared.ts';
const WEEKDAY_NAMES_HI = ['सोमवार', 'मंगलवार', 'बुधवार', 'गुरुवार', 'शुक्रवार', 'शनिवार', 'रविवार'] as const;
const MONTH_NAMES_HI = ['जनवरी', 'फ़रवरी', 'मार्च', 'अप्रैल', 'मई', 'जून', 'जुलाई', 'अगस्त', 'सितंबर', 'अक्टूबर', 'नवंबर', 'दिसंबर'] as const;
const WORKWEEK_HI = ['सोमवार', 'मंगलवार', 'बुधवार', 'गुरुवार', 'शुक्रवार'] as const;
function formatHindiWallTime(hour: number, minute: number, second: number) { const suffix = hour >= 12 ? 'PM' : 'AM'; const hour12 = hour % 12 || 12; if (second) return `${hour12}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')} ${suffix}`; if (minute) return `${hour12}:${String(minute).padStart(2, '0')} ${suffix}`; return `${hour12} ${suffix}`; }
export const HI_LOCALE: ToTextLocaleDefinition = {
  intl: 'hi', weekdayNames: WEEKDAY_NAMES_HI, monthNames: MONTH_NAMES_HI, conjunction: 'और', customSource: 'कस्टम स्रोत', customSet: 'कस्टम सेट', weekdayShortcut: 'कार्यदिवस',
  everyUnit(freq, interval) { switch (freq) { case Frequency.YEARLY: return interval === 1 ? 'हर साल' : `हर ${interval} साल`; case Frequency.MONTHLY: return interval === 1 ? 'हर महीना' : `हर ${interval} महीने`; case Frequency.WEEKLY: return interval === 1 ? 'हर सप्ताह' : `हर ${interval} सप्ताह`; case Frequency.DAILY: return interval === 1 ? 'हर दिन' : `हर ${interval} दिन`; case Frequency.HOURLY: return interval === 1 ? 'हर घंटा' : `हर ${interval} घंटे`; case Frequency.MINUTELY: return interval === 1 ? 'हर मिनट' : `हर ${interval} मिनट`; case Frequency.SECONDLY: return interval === 1 ? 'हर सेकंड' : `हर ${interval} सेकंड`; } },
  ordinalNumber(value) { if (value < 0) return value === -1 ? 'अंतिम' : `${Math.abs(value)}वां अंतिम`; return `${value}वां`; },
  formatWeekday(value) { const name = WEEKDAY_NAMES_HI[value.weekday]!; if (!value.ordinal) return name; if (value.ordinal === -1) return `अंतिम ${name}`; return `${value.ordinal}वां ${name}`; },
  formatWallTime: formatHindiWallTime,
  formatDate(date, tzid) { return formatLocalizedDate(date, tzid, 'hi'); }, tzAbbreviation(date, tzid) { return formatTzAbbreviation(date, tzid, 'hi'); }, countPhrase(count) { return `${count} ${count === 1 ? 'बार' : 'बार'}`; }, dateCountPhrase(count, additional) { return additional ? `${count} अतिरिक्त ${count === 1 ? 'तारीख' : 'तारीखें'}` : `${count} ${count === 1 ? 'तारीख' : 'तारीखें'}`; }, sourceDateCountPhrase(count) { return `${count} ${count === 1 ? 'तारीख' : 'तारीखें'}`; }, withAdditionalDates(count) { return `${count} अतिरिक्त ${count === 1 ? 'तारीख के साथ' : 'तारीखों के साथ'}`; }, excludingDates(count) { return `${count} ${count === 1 ? 'तारीख को छोड़कर' : 'तारीखें छोड़कर'}`; }, excludingPhrase(value) { return `${value} को छोड़कर`; }, exceptPhrase(value) { return `${value} को छोड़कर`; }, weekPhrase(value) { return `सप्ताह ${value} में`; }, monthsPhrase(months) { return `${months} में`; }, weekdaysPhrase(weekdays) { return `${joinList(weekdays, 'और', 'hi')} को`; }, monthDaysPhrase(days) { return `महीने के ${joinList(days, 'और', 'hi')} दिन`; }, yearDaysPhrase(days) { return `साल के ${joinList(days, 'और', 'hi')} दिन`; }, timePhrase(times) { return `${times} पर`; }, minutesPhrase(minutes) { return `मिनट ${minutes} पर`; }, secondsPhrase(seconds) { return `सेकंड ${seconds} पर`; }, untilPhrase(date) { return `${date} तक`; }, countLimitPhrase(count) { return `${count} ${count === 1 ? 'बार तक' : 'बार तक'}`; }, dtstartPhrase(date) { return `${date} से शुरू`; }, setPosPhrase(instances, count) { return `${instances} ${count === 1 ? 'बार' : 'बार'}`; }, weekStartsOnPhrase(weekday) { return `सप्ताह ${weekday} से शुरू`; }, rscalePhrase(rscale, skip) { return `(RSCALE=${rscale}${skip ? `;SKIP=${skip}` : ''})`; }, mergeWeekdayShortcut(weekdays) { const sorted = [...weekdays].sort(); const expected = [...WORKWEEK_HI].sort(); return sorted.length === expected.length && sorted.every((day, index) => day === expected[index]) ? 'कार्यदिवस' : null; }, weekdayShortcutPhrase() { return 'हर कार्यदिवस'; },
};
