import { Frequency } from '../options.ts';
import { formatLocalizedDate, formatTzAbbreviation, joinList, type ToTextLocaleDefinition } from './shared.ts';
const WEEKDAY_NAMES_YUE = ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'] as const;
const MONTH_NAMES_YUE = ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'] as const;
const WORKWEEK_YUE = ['星期一', '星期二', '星期三', '星期四', '星期五'] as const;
function formatYueWallTime(hour: number, minute: number, second: number) { if (second) return `${hour}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`; if (minute) return `${hour}:${String(minute).padStart(2, '0')}`; return `${hour}時`; }
export const YUE_HANT_LOCALE: ToTextLocaleDefinition = {
  intl: 'yue-Hant', weekdayNames: WEEKDAY_NAMES_YUE, monthNames: MONTH_NAMES_YUE, conjunction: '和', customSource: '自訂來源', customSet: '自訂集合', weekdayShortcut: '平日',
  everyUnit(freq, interval) { switch (freq) { case Frequency.YEARLY: return interval === 1 ? '每年' : `每 ${interval} 年`; case Frequency.MONTHLY: return interval === 1 ? '每月' : `每 ${interval} 月`; case Frequency.WEEKLY: return interval === 1 ? '每週' : `每 ${interval} 週`; case Frequency.DAILY: return interval === 1 ? '每日' : `每 ${interval} 日`; case Frequency.HOURLY: return interval === 1 ? '每小時' : `每 ${interval} 小時`; case Frequency.MINUTELY: return interval === 1 ? '每分鐘' : `每 ${interval} 分鐘`; case Frequency.SECONDLY: return interval === 1 ? '每秒' : `每 ${interval} 秒`; } },
  ordinalNumber(value) { if (value < 0) return value === -1 ? '最後' : `倒數第${Math.abs(value)}`; return `第${value}`; },
  formatWeekday(value) { const name = WEEKDAY_NAMES_YUE[value.weekday]!; if (!value.ordinal) return name; if (value.ordinal === -1) return `最後${name}`; return `第${value.ordinal}${name}`; },
  formatWallTime: formatYueWallTime,
  formatDate(date, tzid) { return formatLocalizedDate(date, tzid, 'zh-Hant'); }, tzAbbreviation(date, tzid) { return formatTzAbbreviation(date, tzid, 'zh-Hant'); }, countPhrase(count) { return `${count} 次`; }, dateCountPhrase(count, additional) { return additional ? `${count} 個額外日期` : `${count} 個日期`; }, sourceDateCountPhrase(count) { return `${count} 個日期`; }, withAdditionalDates(count) { return `帶有 ${count} 個額外日期`; }, excludingDates(count) { return `排除 ${count} 個日期`; }, excludingPhrase(value) { return `排除 ${value}`; }, exceptPhrase(value) { return `除 ${value}`; }, weekPhrase(value) { return `喺第 ${value} 週`; }, monthsPhrase(months) { return `喺 ${months}`; }, weekdaysPhrase(weekdays) { return `喺 ${joinList(weekdays, '和', 'zh-Hant')}`; }, monthDaysPhrase(days) { return `喺每月第 ${joinList(days, '和', 'zh-Hant')} 日`; }, yearDaysPhrase(days) { return `喺每年第 ${joinList(days, '和', 'zh-Hant')} 日`; }, timePhrase(times) { return `喺 ${times}`; }, minutesPhrase(minutes) { return `喺第 ${minutes} 分鐘`; }, secondsPhrase(seconds) { return `喺第 ${seconds} 秒`; }, untilPhrase(date) { return `直到 ${date}`; }, countLimitPhrase(count) { return `共 ${count} 次`; }, dtstartPhrase(date) { return `由 ${date} 開始`; }, setPosPhrase(instances, count) { return `喺第 ${instances} ${count === 1 ? '次' : '次'}`; }, weekStartsOnPhrase(weekday) { return `每週由 ${weekday} 開始`; }, rscalePhrase(rscale, skip) { return `(RSCALE=${rscale}${skip ? `;SKIP=${skip}` : ''})`; }, mergeWeekdayShortcut(weekdays) { const sorted = [...weekdays].sort(); const expected = [...WORKWEEK_YUE].sort(); return sorted.length === expected.length && sorted.every((day, index) => day === expected[index]) ? '平日' : null; }, weekdayShortcutPhrase() { return '每個平日'; },
};
